exclude: .*migrations\/.*
repos:
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
    - manual
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-mutable
    - flake8-print
    - flake8-simplify
    - flake8-pyproject
    exclude: settings.py
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
- hooks:
  - entry: poetry run pylint
    exclude: manage.py
    id: pylint
    language: python
    name: pylint
    types:
    - python
  repo: local
- hooks:
  - id: seed-isort-config
  repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
- hooks:
  - id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 23.11.0
- hooks:
  - additional_dependencies:
    - django
    - djangorestframework
    - python-dotenv
    - django-taggit
    - pymysql
    - types-pymysql
    - djangorestframework-stubs
    - django-stubs
    - django-phonenumber-field
    - phonenumbers
    - drf-nested-routers
    - djangorestframework-simplejwt
    - django-autoslug
    - django-cors-headers
    - drf-yasg[validation]
    args:
    - --no-strict-optional
    - --ignore-missing-imports
    exclude: settings.py
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
- hooks:
  - additional_dependencies:
    - .[toml]
    args:
    - -c
    - pyproject.toml
    id: bandit
  repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
- hooks:
  - id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
- hooks:
  - args:
    - -f
    - requirements.txt
    - -o
    - requirements.txt
    - --without-hashes
    id: poetry-export
  repo: https://github.com/python-poetry/poetry
  rev: 1.7.0
